language: php
php:
  - 5.4
env:
  - DB=mysqli MOODLE_VERSION=MOODLE_28_STABLE
  - DB=pgsql MOODLE_VERSION=MOODLE_28_STABLE
  - DB=mysqli MOODLE_VERSION=MOODLE_29_STABLE
  - DB=pgsql MOODLE_VERSION=MOODLE_29_STABLE
  - DB=mysqli MOODLE_VERSION=master
  - DB=pgsql MOODLE_VERSION=master
before_script:
 - git clone git://github.com/moodle/moodle ../moodle
 - cd ../moodle
 - git checkout $MOODLE_VERSION
 - sudo apt-get update > /dev/null
 - composer self-update
 - phpenv rehash
 - sh -c "if [ '$MOODLE_VERSION' = 'MOODLE_28_STABLE' ]; then composer install --dev; fi"

 - mv ../moodle-mod_jclic mod/jclic
 - cp config-dist.php config.php
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*phpu\)%\n\1%' config.php"
 - sh -c "sed -i -e 's%\(\$CFG.*bht\)%\n\1%' config.php"

 - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; fi"
 - sh -c "if [ '$DB' = 'mysqli' ]; then sed -i -e s/\'pgsql\'/\'mysqli\'/ -e s/\'username\'/\'root\'/ config.php; fi"

 - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database moodle;' -U postgres; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then sed -i s/\'username\'/\'postgres\'/ config.php; fi"
 - mkdir -m777 $HOME/moodledata

 - php admin/tool/phpunit/cli/init.php
script:
 - vendor/bin/phpunit mod_jclic_lib_testcase ./mod/jclic/tests/lib_test.php
