language: php
matrix:
  include:
    - php: 5.3
      env: DB=mysqli MOODLE_VERSION=MOODLE_26_STABLE
    - php: 5.3
      env: DB=pgsql MOODLE_VERSION=MOODLE_26_STABLE
    - php: 5.4
      env: DB=mysqli MOODLE_VERSION=MOODLE_27_STABLE
    - php: 5.4
      env: DB=pgsql MOODLE_VERSION=MOODLE_27_STABLE
    - php: 5.4
      env: DB=mysqli MOODLE_VERSION=MOODLE_28_STABLE
    - php: 5.4
      env: DB=pgsql MOODLE_VERSION=MOODLE_28_STABLE
    - php: 5.4
      env: DB=mysqli MOODLE_VERSION=master
    - php: 5.4
      env: DB=pgsql MOODLE_VERSION=master
before_script:

 - git clone git://github.com/moodle/moodle ../moodle
 - cd ../moodle
 - git checkout $MOODLE_VERSION
 - sudo apt-get update > /dev/null
 - composer self-update
 - composer install --dev --prefer-dist
 - pear channel-discover pear.phpunit.de
 - pear channel-discover pear.symfony.com
 - pear install pear.phpunit.de/DbUnit
 - phpenv rehash

 - mv ../moodle-mod_jclic mod/jclic
 - cp config-dist.php config.php
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*phpu\)%\n\1%' config.php"
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*bht\)%\n\1%' config.php"
 - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; fi"
 - sh -c "if [ '$DB' = 'mysqli' ]; then sed -i -e s/\'pgsql\'/\'mysqli\'/ -e s/\'username\'/\'root\'/ config.php; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database moodle;' -U postgres; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then sed -i s/\'username\'/\'postgres\'/ config.php; fi"
 - mkdir -m777 $HOME/moodledata

 - php admin/tool/phpunit/cli/init.php
script:
 - vendor/bin/phpunit mod_jclic_lib_testcase ./mod/jclic/tests/lib_test.php
